# Site settings
title: 'CS373 Spring 2016: Robert Lynch'
description: 'My blog for Software Engineering, Spring 2016'
url: 'http://bobertforever.github.io/cs373-blog/'
baseurl: '/cs373-blog/'
google_analytics: 'UA-48035110-5'

author:
  name: 'Robert Lynch'
  email: robertlynch2012@gmail.com
  github_username:  BobertForever

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: pygments

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
